# Site settings
title:       Benjamin Guillet
email:       contact@benjaminguillet.com
author:      Benjamin Guillet
description: "Benjamin Guillet, Software Engineer. Between France and USA!."
baseurl:     ""
url:         "http://www.benjaminguillet.com"

# Google analytics
google_analytics: UA-28793596-2

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: true
github_username: benjamin-guillet
twitter_username: ben_guillet
google_plus_id:
linkedin_username: benjaminguillet/en
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     5
sass:
  compressed: true
